export enum PopupElementId {
  COUNT_BADGE = 'count-badge',
  BANNER_DOT = 'banner-dot',
  BANNER_STATUS_TEXT = 'banner-status-text',
  SAVE_CURRENT_BTN = 'save-current-btn',
  SAVE_BTN_TEXT = 'save-btn-text',
  SEARCH_INPUT = 'search-input',
  PRODUCTS_LIST = 'products-list',
  EXPORT_JSON_BTN = 'export-json-btn',
  CLEAR_ALL_BTN = 'clear-all-btn',
  DETAILS_MODAL = 'details-modal',
  CLOSE_MODAL_BTN = 'close-modal-btn',
  MODAL_PRODUCT_ASIN = 'modal-product-asin',
  MODAL_BODY_CONTENT = 'modal-body-content',
  OPEN_SETTINGS_BTN = 'open-settings-btn',
  SETTINGS_MODAL = 'settings-modal',
  CLOSE_SETTINGS_MODAL_BTN = 'close-settings-modal-btn',
  SETTING_MARKUP_PCT = 'setting-markup-pct',
  SETTING_FORMAT = 'setting-format',
  SETTING_BID_PCT = 'setting-bid-pct',
  SETTING_DURATION = 'setting-duration',
  SETTING_IMMEDIATE_PAY = 'setting-immediate-pay',
  SETTING_ALLOW_OFFERS = 'setting-allow-offers',
  SAVE_SETTINGS_BTN = 'save-settings-btn',
  AUCTION_SETTINGS_GROUP = 'auction-settings-group'
}
